### PR TITLE
Add 'rezenbekk' to students.txt (Issue #14)

### PR DESCRIPTION
**Pull request by Rezenbekk**
#14

### CODE REVIEW

**Comment by Rezenbekk** [comment]
How the f.. hell do you just add to a file?

**Comment by malinink** [comment]
@Rezenbekk 
Your PR seems to be OK right now.
Still having problems?

**Comment by Rezenbekk** [comment]
Not at the moment, thank you very much!

**Comment by Rezenbekk** [comment]
link: #14

**Pull request closed without merging**
