### PR TITLE
Feature 80

### PR DESCRIPTION
**Pull request by vkpankov**
Issue https://github.com/malinink/web2016-test/issues/80

### CODE REVIEW

**Comment by malinink** [comment]
@vkpankov Provide link to issue in PR.

**Comment by vkpankov** [comment]
@malinink , https://github.com/malinink/web2016-test/issues/80

**Comment by malinink** [comment]
@vkpankov 
Please edit PR description and put link there!

**Comment by vkpankov** [comment]
@malinink , done

**Comment by malinink** [comment]
@vkpankov GJ

**Pull request closed without merging**
